
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  flask-app:
    image: priyanshuatfinstack/flask-app:latest
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/myapp
      - SECRET_KEY=xoufgwugregreguhrohgoerthoier
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: overlay
    attachable: true